### ISSUE TITLE
meeting-qt项目编译异常

### ISSUE THREAD

**Issue by Always17365** [GrowthEase/NetEase_Meeting#43]
你好，meeting-qt项目中yunxin-conan.netease.im的域名无法访问，无法下载SDK包信息
[cmake] ERROR: HTTPConnectionPool(host='yunxin-conan.netease.im', port=8081): Max retries exceeded with url: /artifactory/api/conan/NetEaseConan/v1/ping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A0D05A8580>, 'Connection to yunxin-conan.netease.im timed out. (connect timeout=60.0)'))

**Comment by nmgwddj** [comment]
您可以尝试将该行代码注释：
https://github.com/GrowthEase/NetEase_Meeting/blob/main/meeting-qt/.cmake/PlatformSettings.cmake#L103
随后在终端输入 `conan remote remove NetEaseConan` 后重新初始化工程。

因新版本 conan 会对同一地址多次尝试导致长时间无法切换到下一个地址，我们会考虑在后续版本种将这里无法访问的地址删除。该地址部署在我们私有化服务器上，因为考虑开发阶段可在私有化环境快速切换地址所以添加了两个 conan 远端。

即使您删除 NetEaseConan 的远端地址也不会影响项目编译，因为依赖组件在 yunxin 远端都已经上传。

希望能帮助您解决问题，祝好。
